# Generated by Django 5.2.6 on 2026-01-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('amountAllocated', models.PositiveIntegerField()),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('EndDate', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.department')),
                ('createdByUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='home.user')),
            ],
        ),
    ]
