# Generated by Django 5.2.6 on 2026-01-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('submittedDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('budgetId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.budget')),
                ('submittedByUserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('expenseApprovalId', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('assignedUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user')),
                ('expenseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.expense')),
            ],
        ),
    ]
