# Generated by Django 5.2.6 on 2026-01-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_budget_enddate_expense_expenseapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='EndDate',
            new_name='endDate',
        ),
    ]
