# Generated by Django 5.2.6 on 2026-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_enddate_budget_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budgetId',
        ),
        migrations.AlterField(
            model_name='budget',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
