# Generated by Django 5.2.6 on 2026-01-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_expense_budgetid_alter_budget_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budgetId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.budget'),
            preserve_default=False,
        ),
    ]
