# Generated by Django 5.2.6 on 2026-01-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_expense_budgetid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='budgetId',
            new_name='budgetIed',
        ),
    ]
