# Generated by Django 5.2.6 on 2026-01-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_budgetid_expense_budgetied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='budgetIed',
            new_name='relatedBudgetId',
        ),
    ]
