# Generated by Django 5.2.6 on 2026-01-23 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_budgetied_expense_relatedbudgetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='endDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
