# Generated by Django 5.2.6 on 2026-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_expense_enddate_expense_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
