# Generated by Django 5.2.6 on 2026-01-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_expense_enddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=10)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('cratedByUserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_notifications', to='home.user')),
                ('toUserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_notifications', to='home.user')),
            ],
        ),
    ]
