# Generated by Django 5.2.6 on 2026-01-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cratedByUserId',
        ),
    ]
