# Generated by Django 5.2.6 on 2026-01-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_notification_cratedbyuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='toUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user'),
        ),
    ]
