# Generated by Django 5.2.6 on 2026-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_userlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='action',
            new_name='action_type',
        ),
        migrations.AddField(
            model_name='userlog',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
