# Generated by Django 5.2.6 on 2026-02-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_action_userlog_action_type_userlog_ipaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='action_type',
            new_name='actionType',
        ),
    ]
