# Generated by Django 5.2.6 on 2026-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_action_type_userlog_actiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
