# Generated by Django 5.2.6 on 2026-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_userlog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='action',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
