# Generated by Django 5.2.6 on 2026-02-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_userlog_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='user',
            new_name='loginUser',
        ),
    ]
