# Generated by Django 5.2.6 on 2026-02-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_user_userlog_loginuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='loginUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logUser', to='home.user'),
        ),
    ]
