# Generated by Django 5.2.6 on 2026-02-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_userlog_loginuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='status',
            new_name='statusCode',
        ),
    ]
