# Generated by Django 5.2.6 on 2026-02-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_status_userlog_statuscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
