# Generated by Django 5.2.6 on 2026-02-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_userlog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='loginUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logUser', to='home.user'),
        ),
    ]
